[passwords]
saukang = 'ClxgXuND'
sandeep = '7M7U97b@'
t-y-lee = '36&2DqBw'
sooken-liew = '!4DW54Gf'
josephine-hendriks = 'wdT89X4&'
meiyun-chan = 'q9Kp64&$'
zack-wong = '@vZJ2444'
guatsiew-loo = 'Tupb#864'
ryan-jung = '3xy7C7&z'
cleavon-lai = 'eD457F2!'
kim-toh = 'g#ZK2t36'
amilia-see = '3^3P$5y8'
xinqi-ng = '4W^u!82!'
azreena = 'Z3U£9td0'
janice-tan = 'BV&e3@8j'
